{% set version = "0.14.0" %}

package:
  name: sensorutils
  version: {{ version }}

source:
  path: ../

build:
  noarch: generic
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  # script: python setup.py install --single-version-externally-managed

requirements:
  host:
    - python >=3.7,<4
    - pip
    - setuptools
  run:
    - python >=3.7,<4
    - numpy >=1.19
    - pandas >=1.2
    - scipy >=1.6

# test:
#   requires:
#     - pytest
#   imports:
#     - sensorutils

about:
  home: https://github.com/haselab-dev/sensorutils
  license: MIT
  license_file: LICENSE
  summary: A utils for sensor data
